EXTRA_VENDOR_LIBRARIES := \
    libandroidicu \
    libaudioclient \
    libaudiomanager \
    libaudiopolicy \
    libbinder \
    libbinderthreadstate \
    libbufferhub \
    libbufferhubqueue \
    libcamera_client \
    libcutils \
    libft2 \
    libgui \
    libharfbuzz_ng \
    libheif \
    libicuuc \
    libicui18n \
    libinput \
    libmedia \
    libmediametrics \
    libmediautils \
    libmemunreachable \
    libminikin \
    libnblog \
    libpackagelistparser \
    libpdx_default_transport \
    libpowermanager \
    libselinux \
    libsonivox \
    libvibrator
